# Generated by Django 4.2.2 on 2023-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
